apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: durable-money-prod

resources:
  - ../../base

images:
  - name: ghcr.io/kamloicc/durable-money-2-microservices-account-service
    newTag: "0.3.1"
