apiVersion: v1
kind: Service
metadata:
  name: transfer-service
  labels:
    app.kubernetes.io/name: transfer-service
    app.kubernetes.io/part-of: durable-money
spec:
  selector:
    app.kubernetes.io/name: transfer-service

  ports:
    - name: http
      port: 8080
      targetPort: http
